# Generated by Django 5.2.6 on 2025-09-28 12:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ems", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="joining_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="job",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
