# Generated by Django 5.2.6 on 2025-09-28 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ems", "0002_alter_employee_joining_date_alter_job_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="name",
            new_name="title",
        ),
    ]
